#!/usr/bin/env node
/**
 * Builds the installable all-in-one plugin ZIP (production hosting needs no Node):
 *
 *   pnpm build:plugin            → dist/plugin/rk-builder/ (staged) + dist/rk-builder-all-in-one.zip
 *   node scripts/package-plugin.mjs --no-zip        stage only (used by the Playground tests)
 *   node scripts/package-plugin.mjs --dev           include tests/
 *   node scripts/package-plugin.mjs --sourcemaps    keep source maps
 *
 * Expects `pnpm build` to have produced dist/public/embed/rk-builder.{js,css} and dist/assets/site.css.
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const src = join(root, "wp-plugin", "rk-builder");
const stage = join(root, "dist", "plugin", "rk-builder");
const zipPath = join(root, "dist", "rk-builder-all-in-one.zip");

const fail = msg => {
  console.error(`package-plugin: ${msg}`);
  process.exit(1);
};

// ---- inputs ----
const embed = join(root, "dist", "public", "embed");
const inputs = {
  js: join(embed, "rk-builder.js"),
  css: join(embed, "rk-builder.css"),
  site: join(root, "dist", "assets", "site.css"),
};
for (const [k, p] of Object.entries(inputs))
  if (!existsSync(p))
    fail(
      `missing ${k} build output ${relative(root, p)} — run \`pnpm build\` first`
    );

// ---- versions must agree ----
const main = readFileSync(join(src, "rk-builder.php"), "utf8");
const header = /^\s*\*\s*Version:\s*([0-9][^\s]*)/m.exec(main)?.[1];
const constant = /define\(\s*'RK_BUILDER_VERSION',\s*'([^']+)'/.exec(main)?.[1];
if (!header || !constant)
  fail("could not read the plugin version from rk-builder.php");
if (header !== constant)
  fail(`plugin header version ${header} != RK_BUILDER_VERSION ${constant}`);

// ---- stage ----
rmSync(join(root, "dist", "plugin"), { recursive: true, force: true });
mkdirSync(stage, { recursive: true });
const skip = new Set([".DS_Store", "node_modules", ".env"]);
cpSync(src, stage, {
  recursive: true,
  filter: p => {
    const rel = relative(src, p);
    if (!rel) return true;
    const parts = rel.split("/");
    if (parts.some(x => skip.has(x) || x.startsWith(".env"))) return false;
    if (!args.has("--dev") && parts[0] === "tests") return false;
    if (parts[0] === "assets") return false; // generated below; never ship stale files from the source tree
    return true;
  },
});

const assets = join(stage, "assets");
mkdirSync(assets, { recursive: true });
const strip = (text, ext) =>
  args.has("--sourcemaps")
    ? text
    : text.replace(
        ext === "js"
          ? /\n?\/\/# sourceMappingURL=.*$/m
          : /\n?\/\*# sourceMappingURL=.*?\*\/\s*$/m,
        ""
      );
const js = strip(readFileSync(inputs.js, "utf8"), "js");
const css = strip(readFileSync(inputs.css, "utf8"), "css");
writeFileSync(join(assets, "builder.js"), js);
writeFileSync(join(assets, "builder.css"), css);
writeFileSync(join(assets, "site.css"), readFileSync(inputs.site, "utf8"));
const hash = createHash("sha1")
  .update(js)
  .update(css)
  .digest("hex")
  .slice(0, 10);
writeFileSync(
  join(assets, "builder.asset.php"),
  `<?php\n// Generated by scripts/package-plugin.mjs - do not edit.\nreturn array( 'dependencies' => array(), 'version' => '${constant}-${hash}' );\n`
);

// ---- validate ----
for (const f of [
  "rk-builder.php",
  "uninstall.php",
  "includes/validation.php",
  "assets/builder.js",
  "assets/builder.css",
  "assets/site.css",
  "assets/builder.asset.php",
]) {
  if (!existsSync(join(stage, f))) fail(`staged plugin is missing ${f}`);
}
const walk = d =>
  readdirSync(d).flatMap(n =>
    statSync(join(d, n)).isDirectory() ? walk(join(d, n)) : [join(d, n)]
  );
const files = walk(stage);
const bad = files.filter(
  f =>
    /(^|\/)(\.env|node_modules)(\/|$)/.test(f) ||
    (!args.has("--sourcemaps") && f.endsWith(".map"))
);
if (bad.length) fail(`forbidden files staged: ${bad.join(", ")}`);
if (!args.has("--sourcemaps") && /sourceMappingURL/.test(js + css))
  fail("source map reference left in production assets");
for (const f of files.filter(
  f => f.endsWith(".php") && !f.includes("/assets/")
)) {
  try {
    execFileSync("php", ["-l", f], { stdio: "pipe" });
  } catch (e) {
    fail(
      `PHP syntax error in ${relative(stage, f)}: ${String(e.stdout ?? e.message).trim()}`
    );
  }
}

console.log(
  `staged ${files.length} files → ${relative(root, stage)} (version ${constant}-${hash})`
);
if (args.has("--no-zip")) process.exit(0);

// ---- zip (top-level folder rk-builder/, as WordPress expects) ----
rmSync(zipPath, { force: true });
try {
  execFileSync("zip", ["-qr", zipPath, "rk-builder", "-x", "*.DS_Store"], {
    cwd: join(root, "dist", "plugin"),
    stdio: "inherit",
  });
} catch {
  fail(
    "the `zip` command is required to create the archive (apt install zip / brew install zip)"
  );
}
const size = (statSync(zipPath).size / 1024).toFixed(0);
console.log(`wrote ${relative(root, zipPath)} (${size} KB)`);
