import type { FieldDef } from "../fields";

export const navbarFields: FieldDef[] = [
  { kind: "group", label: "Announcement bar" },
  {
    kind: "text",
    key: "topText",
    label: "Message",
    maxLength: 160,
    help: "A strip above the header, e.g. “Free estimates this month”. Leave empty for none.",
  },
  { kind: "text", key: "topLabel", label: "Link text", maxLength: 40 },
  { kind: "url", key: "topHref", label: "Link address", maxLength: 500 },
  {
    kind: "select",
    key: "topTone",
    label: "Bar colour",
    options: [
      { value: "primary", label: "Primary colour" },
      { value: "dark", label: "Dark" },
      { value: "light", label: "Light" },
    ],
  },
  {
    kind: "checkbox",
    key: "topDismiss",
    label: "Let visitors close the announcement bar",
    help: "Adds a close button. It stays closed in that visitor's browser until you change the message.",
  },
  { kind: "group", label: "Brand" },
  { kind: "text", key: "brand", label: "Brand name", maxLength: 80 },
  {
    kind: "media",
    key: "logoUrl",
    idKey: "logoMediaId",
    label: "Logo",
    optional: true,
  },
  {
    kind: "select",
    key: "logoSize",
    label: "Logo size",
    options: [
      { value: "sm", label: "Small (40 px)" },
      { value: "md", label: "Medium (64 px)" },
      { value: "lg", label: "Large (88 px)" },
    ],
  },
  { kind: "group", label: "Menu" },
  {
    kind: "textarea",
    key: "links",
    label: "Menu links",
    maxLength: 3000,
    help: "One per line: Label|/path (up to 12). Start a line with “- ” to put it in a drop-down under the line above (up to 8 each), e.g. “- Web design|/services/web-design”. Add a short description after a second bar to show it under the item: “- Hardwood|/services/hardwood|New floors, any species”.",
  },
  {
    kind: "select",
    key: "align",
    label: "Menu position",
    options: [
      { value: "spread", label: "Centre, between logo and buttons" },
      { value: "left", label: "Next to the logo" },
    ],
  },
  { kind: "group", label: "Buttons" },
  { kind: "text", key: "phone", label: "Phone button text", maxLength: 40 },
  {
    kind: "url",
    key: "phoneHref",
    label: "Phone button link",
    maxLength: 500,
    help: "e.g. tel:+13098635246",
  },
  {
    kind: "text",
    key: "ctaText",
    label: "Extra button text",
    maxLength: 40,
    help: "A second button, e.g. “Get a quote”. Leave empty for none.",
  },
  {
    kind: "url",
    key: "ctaHref",
    label: "Extra button link",
    maxLength: 500,
  },
  {
    kind: "select",
    key: "buttons",
    label: "Button style",
    options: [
      { value: "auto", label: "Automatic (follows the bar)" },
      { value: "solid", label: "Filled" },
      { value: "outline", label: "Outlined" },
    ],
  },
  { kind: "group", label: "Appearance" },
  {
    kind: "select",
    key: "bg",
    label: "Bar colour",
    options: [
      { value: "auto", label: "Automatic (site background)" },
      { value: "light", label: "Light" },
      { value: "dark", label: "Dark" },
      { value: "primary", label: "Primary colour" },
    ],
  },
  {
    kind: "select",
    key: "size",
    label: "Bar height",
    options: [
      { value: "compact", label: "Compact" },
      { value: "regular", label: "Regular" },
      { value: "tall", label: "Tall" },
    ],
  },
  {
    kind: "checkbox",
    key: "shadow",
    label: "Shadow under the bar",
  },
  {
    kind: "checkbox",
    key: "shrink",
    label: "Slim down and add a shadow when scrolling",
  },
  {
    kind: "checkbox",
    key: "overlay",
    label: "Overlay the hero below (transparent, light text)",
  },
];
